/* Autogenerated Testbench for wallace_multiplier */
`include "wallace_multiplier_rca.v"
`timescale 1ns / 1ps
module wallace_multiplier_tb;
  reg  [25:0] a;
  reg  [23:0] b;
  wire [49:0] p;
  wire [49:0] ref;

  wallace_multiplier uut(.a(a), .b(b), .p(p));
  assign ref = a * b;
  integer i;
  initial begin
    $display("a, b, result, expected");
    for (i = 0; i < 20; i = i+1) begin
      a = $random;
      b = $random;
      
      #1;
      $display("%d * %d = %d (got %d)", a, b, ref, p);
      if (p !== a*b) $display("Mismatch detected!");
    end
    $finish;
  end
endmodule